ALTER TABLE IF EXISTS accounts DROP CONSTRAINT IF EXISTS owner_currency_key;

ALTER TABLE IF EXISTS accounts DROP CONSTRAINT IF EXISTS accounts_owner_fkey;

DROP TABLE IF EXISTS users;

DROP FUNCTION IF EXISTS decrypt_data;

DROP FUNCTION IF EXISTS encrypt_data;

DROP EXTENSION IF EXISTS pgcrypto;