// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  hashed_pass,
  full_name,
  email
) VALUES (
  $1, $2, $3, $4
) RETURNING username, hashed_pass, full_name, email, email_encrypt, password_changed_at, created_at
`

type CreateUserParams struct {
	Username   string `json:"username"`
	HashedPass string `json:"hashed_pass"`
	FullName   string `json:"full_name"`
	Email      string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.HashedPass,
		arg.FullName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPass,
		&i.FullName,
		&i.Email,
		&i.EmailEncrypt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, hashed_pass, full_name, email, email_encrypt, password_changed_at, created_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPass,
		&i.FullName,
		&i.Email,
		&i.EmailEncrypt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  hashed_pass = COALESCE($1, hashed_pass),
  password_changed_at = COALESCE($2, password_changed_at),
  full_name = COALESCE($3, full_name),
  email = COALESCE($4, email)
WHERE
  username = $5
RETURNING username, hashed_pass, full_name, email, email_encrypt, password_changed_at, created_at
`

type UpdateUserParams struct {
	HashedPass        pgtype.Text        `json:"hashed_pass"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	FullName          pgtype.Text        `json:"full_name"`
	Email             pgtype.Text        `json:"email"`
	Username          string             `json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.HashedPass,
		arg.PasswordChangedAt,
		arg.FullName,
		arg.Email,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPass,
		&i.FullName,
		&i.Email,
		&i.EmailEncrypt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}
